name: Test for Review
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lock-file
      - name: Lint Check
        run: yarn lint
      - name: Format Check
        run: yarn fmt --check
      - name: Run Test
        run: yarn test
  
